/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesChar123LocaleChar125RouteImport } from './routes/use-cases/{-$locale}'
import { Route as TechnologyChar123LocaleChar125RouteImport } from './routes/technology/{-$locale}'
import { Route as PricingChar123LocaleChar125RouteImport } from './routes/pricing/{-$locale}'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesChar123LocaleChar125Route =
  UseCasesChar123LocaleChar125RouteImport.update({
    id: '/use-cases/{-$locale}',
    path: '/use-cases/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const TechnologyChar123LocaleChar125Route =
  TechnologyChar123LocaleChar125RouteImport.update({
    id: '/technology/{-$locale}',
    path: '/technology/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const PricingChar123LocaleChar125Route =
  PricingChar123LocaleChar125RouteImport.update({
    id: '/pricing/{-$locale}',
    path: '/pricing/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{-$locale}': typeof Char123LocaleChar125Route
  '/pricing/{-$locale}': typeof PricingChar123LocaleChar125Route
  '/technology/{-$locale}': typeof TechnologyChar123LocaleChar125Route
  '/use-cases/{-$locale}': typeof UseCasesChar123LocaleChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/{-$locale}': typeof Char123LocaleChar125Route
  '/pricing/{-$locale}': typeof PricingChar123LocaleChar125Route
  '/technology/{-$locale}': typeof TechnologyChar123LocaleChar125Route
  '/use-cases/{-$locale}': typeof UseCasesChar123LocaleChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{-$locale}': typeof Char123LocaleChar125Route
  '/pricing/{-$locale}': typeof PricingChar123LocaleChar125Route
  '/technology/{-$locale}': typeof TechnologyChar123LocaleChar125Route
  '/use-cases/{-$locale}': typeof UseCasesChar123LocaleChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$locale}'
    | '/pricing/{-$locale}'
    | '/technology/{-$locale}'
    | '/use-cases/{-$locale}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/{-$locale}'
    | '/pricing/{-$locale}'
    | '/technology/{-$locale}'
    | '/use-cases/{-$locale}'
  id:
    | '__root__'
    | '/'
    | '/{-$locale}'
    | '/pricing/{-$locale}'
    | '/technology/{-$locale}'
    | '/use-cases/{-$locale}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125Route
  PricingChar123LocaleChar125Route: typeof PricingChar123LocaleChar125Route
  TechnologyChar123LocaleChar125Route: typeof TechnologyChar123LocaleChar125Route
  UseCasesChar123LocaleChar125Route: typeof UseCasesChar123LocaleChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/{-$locale}': {
      id: '/use-cases/{-$locale}'
      path: '/use-cases/{-$locale}'
      fullPath: '/use-cases/{-$locale}'
      preLoaderRoute: typeof UseCasesChar123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/{-$locale}': {
      id: '/technology/{-$locale}'
      path: '/technology/{-$locale}'
      fullPath: '/technology/{-$locale}'
      preLoaderRoute: typeof TechnologyChar123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/{-$locale}': {
      id: '/pricing/{-$locale}'
      path: '/pricing/{-$locale}'
      fullPath: '/pricing/{-$locale}'
      preLoaderRoute: typeof PricingChar123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123LocaleChar125Route: Char123LocaleChar125Route,
  PricingChar123LocaleChar125Route: PricingChar123LocaleChar125Route,
  TechnologyChar123LocaleChar125Route: TechnologyChar123LocaleChar125Route,
  UseCasesChar123LocaleChar125Route: UseCasesChar123LocaleChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
